"""empty message

Revision ID: 345c5eac33a7
Revises: 8d34b315633f
Create Date: 2022-02-21 11:59:38.519293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345c5eac33a7'
down_revision = '8d34b315633f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('park_list_joins_list_id_fkey', 'park_list_joins', type_='foreignkey')
    op.create_foreign_key(None, 'park_list_joins', 'lists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'park_list_joins', type_='foreignkey')
    op.create_foreign_key('park_list_joins_list_id_fkey', 'park_list_joins', 'users', ['list_id'], ['id'])
    # ### end Alembic commands ###
