"""empty message

Revision ID: 534e889b94aa
Revises: 345c5eac33a7
Create Date: 2022-04-05 12:17:47.536250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534e889b94aa'
down_revision = '345c5eac33a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parks', sa.Column('address', sa.String(length=40), nullable=False))
    op.add_column('parks', sa.Column('zip_code', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parks', 'zip_code')
    op.drop_column('parks', 'address')
    # ### end Alembic commands ###
